name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
       
    - name: build sender
      run: g++ -Wall -Wextra -o testsender TestSender.cpp BMS_Sender.c
  
    - name: Run Sender
      run: ./testsender
  
    - name: build receiver
      run: g++ -Wall -Wextra -o testreceiver BMS_Receiver.c


      
    - name: Pipeline sender/receiver
      run: ./testsender | ./testreceiver

